semi: false
singleQuote: true
trailingComma: none
tabWidth: 2
printWidth: 60
arrowParens: avoid
endOfLine: lf
vueIndentScriptAndStyle: true
htmlWhitespaceSensitivity: strict
tsxBracketSameLine: true
plugins:
  - 'prettier-plugin-tailwindcss'
  - 'prettier-plugin-classnames'
  - 'prettier-plugin-merge'
